context:
  version: "0.11.2"
  build_number: 0

package:
  name: xeus-r
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-r/archive/${{ version }}.tar.gz
  sha256: 48ac9c46800f46b8263e3f27c53eb1568a35297fb61a8abbb359ce548493025a

build:
  number: ${{ build_number }}
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/
    missing_dso_allowlist:
      - if: win
        then:
          - '*/R.dll'

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then:
        - make
    - pkg-config
    # Dependencies for hera
    - if: build_platform != target_platform
      then:
        - r-base
        - cross-r-base
        - r-cli
        - r-evaluate
        - r-glue
        - r-IRDisplay
        - r-jsonlite
        - r-r6
        - r-repr
        - r-rlang
  host:
    - xeus >=6,<7
    - xeus-zmq >=4.0,<5.0
    - nlohmann_json >=3.11.3,<4
    - nlohmann_json-abi
    - r-base
    # Dependencies for hera
    - r-cli
    - r-evaluate
    - r-glue
    - r-IRdisplay
    - r-jsonlite
    - r-r6
    - r-repr
    - r-rlang
  run:
    - r-base
    - r-cli
    - r-evaluate
    - r-glue
    - r-IRdisplay
    - r-jsonlite
    - r-r6
    - r-repr
    - r-rlang

tests:
  - package_contents:
      files:
        exists:
          - ${{ "Library/" if win }}bin/xr${{ ".exe" if win }}
          - ${{ "Library/" if win }}share/jupyter/kernels/xr/kernel.json
          - ${{ "Library/" if win }}include/xeus-r/xinterpreter.hpp
          - ${{ "Library/" if win }}lib/cmake/xeus-r/xeus-rConfig.cmake
          - ${{ "Library/" if win }}lib/cmake/xeus-r/xeus-rConfigVersion.cmake
          - if: unix
            then:
              - lib/R/library/hera/R/hera.rdb

about:
  homepage: https://github.com/jupyter-xeus/xeus-r
  repository: https://github.com/jupyter-xeus/xeus-r
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: R kernel for Jupyter based on xeus
  description: Jupyter kernel for the R programming language
  documentation: https://xeus-r.readthedocs.io

extra:
  recipe-maintainers:
    - IsabelParedes
    - JohanMabille
    - DerThorsten
    - SylvainCorlay
    - romainfrancois
